### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by saivert** [gnif/LookingGlass#168]
I'm attempting to get the ball rolling on a flatpak for looking glass client.

This is more like feature tracking issue.

Access to the shared memory file needs to be solved before this can work.

```json
{
    "app-id": "com.hostfission.looking-glass",
    "branch": "stable",
    "runtime": "org.freedesktop.Platform",
    "runtime-version": "18.08",
    "sdk": "org.freedesktop.Sdk",
    "command": "looking-glass-client",
    "finish-args": [
        "--share=ipc",
        "--device=dri",
        "--socket=x11",
        "--share=network",
        "--device=all"
    ],
    "modules": [
        {
            "name": "spice-protocol",
            "buildsystem": "meson",
            "sources": [
                {
                    "type": "archive",
                    "url": "https://www.spice-space.org/download/releases/spice-protocol/spice-protocol-0.14.0.tar.bz2",
                    "sha256": "b6a4aa1ca32668790b45a494bbd000e9d05797b391d5a5d4b91adf1118216eac"
                }
            ]
        },
        {
            "name": "glu",
            "config-opts": ["--disable-static"],
            "sources": [
                {
                    "type": "archive",
                    "url": "https://mesa.freedesktop.org/archive/glu/glu-9.0.0.tar.bz2",
                    "sha256": "1f7ad0d379a722fcbd303aa5650c6d7d5544fde83196b42a73d1193568a4df12"
                }
            ],
            "cleanup": [ "/include", "/lib/*.a", "/lib/*.la", "/lib/pkgconfig" ]
        },
        {
            "name": "looking-glass-client",
            "buildsystem": "cmake",
            "build-commands": [
                "cp /usr/lib/x86_64-linux-gnu/libbfd*.so /app/lib/"
            ],
            "subdir": "client",
            "sources": [
                {
                    "type": "archive",
                    "url": "https://looking-glass.hostfission.com/ci/host/source?id=18",
                    "sha256": "bdf8e20f6bf93710f59c3f0991e411e681460a091fd7737646e112c6daf98141",
                    "dest-filename": "LookingGlass-780bb248f7b8dd65b102ecd5010877f99bb8095e.zip"
                }
            ]
        }
    ]
}
```

This is as far as I have gotten:

```
$ flatpak run com.hostfission.looking-glass 
[I]               main.c:966  | run                            | Looking Glass (B1-rc4-0-g026bdb00f2+1)
[I]               main.c:967  | run                            | Locking Method: Atomic
[I]                egl.c:187  | egl_initialize                 | Double buffering is on
[I]                egl.c:201  | egl_initialize                 | Multsampling enabled, max samples: 4
[I]               main.c:902  | try_renderer                   | Using Renderer: EGL
[I]               main.c:1128 | run                            | Using Clipboard: X11
[E]               main.c:856  | map_memory                     | Failed to stat the shared memory file: /dev/shm/looking-glass
[E]               main.c:1157 | run                            | Failed to map memory
```

EDIT: It turns out this can work if you instruct qemu to place the shared memory file other than in `/dev/shm` directory and you make sure it has the right ownership. But we need to figure out how to make this more user friendly.

**Comment by gnif** [comment]
Issues are for Looking Glass bugs or feature requests, your issue is a packaging issue and not a Looking Glass issue.

If you do not use "/dev/shm" for the shared memory file you will lose performance, there is a reason why this path is used.

**Comment by ChrisTucker2000** [comment]
@saivert Have you made any progress on this? It's a nightmare to get this thing running properly, so I was thinking of putting together a Flatpak that makes it nice and easy - then saw this issue. What's the current status of this?

**Comment by saivert** [comment]
@ChrisTucker2000 no I abandoned the project.
But you would need flatpak to support opening up holes in the sandbox to the /dev/shm path as a start I guess.
But that would only solve part of the user friendlyness problem. Having the looking glass client in a flatpak is only half the battle as you cannot simply install the flatpak and run it and expect things to work.

**Comment by gasinvein** [comment]
@saivert FYI flatpak now supports `--device=shm` arg to allow access to `/dev/shm`.

**Comment by anthr76** [comment]
Update on this incase anyone is interested 

![image](https://user-images.githubusercontent.com/25143877/118369009-be622600-b570-11eb-9c93-693a60549730.png)


Got this working so far like so 

```yaml
---
app-id: io.lookingglass.client
branch: stable
runtime: org.freedesktop.Platform
runtime-version: '20.08'
sdk: org.freedesktop.Sdk
command: looking-glass-client
finish-args:
- "--share=ipc"
- "--device=dri"
- "--socket=x11"
- "--socket=wayland"
- "--share=network"
- "--device=shm"
- "--device=kvm"
- "--env=SDL_VIDEODRIVER="
- "--unset-env=SDL_VIDEODRIVER"
modules:
- name: spice-protocol
  buildsystem: meson
  sources:
  - type: archive
    url: https://www.spice-space.org/download/releases/spice-protocol/spice-protocol-0.14.0.tar.bz2
    sha256: b6a4aa1ca32668790b45a494bbd000e9d05797b391d5a5d4b91adf1118216eac
- name: looking-glass-client
  buildsystem: cmake
  build-commands:
  - install -Dm755 /usr/lib/$(gcc -print-multiarch)/libbfd-*.so -t ${FLATPAK_DEST}/lib
  subdir: client
  sources:
  - type: git
    url: https://github.com/gnif/LookingGlass.git
    tag: B3
    commit: 2973319bff80bf1531265bdbec6707bdda3f40eb
 ```
 
 Just need to work through some wayland/X quirks and I think tag the version in the manifest? Not super familiar with flatpak building just yet. @gnif if it's alright with you once this is cleaned up I would like to publish it to flathub. Going to work on it a little bit more tonight
